### ISSUE TITLE
Default Storageclass is needed as a prerequisite

### ISSUE THREAD

**Issue by anencore94** [hongkunyoo/jupyterflow#4]
First of all, Thanks a lot for maintaining such a nice repo!!

I've been followed the guide with "Set up on JupyterHub", I found there needs one more prerequisite : "Setup **Default Storageclass** before helm install jupyterhub"

Otherwise, the deployment "hub" in jupyterflow namespace will at PENDING status forever, as well as the corresponding pvc "hub-db-dir"

I think it is not the jupyterflow's mistake, but the jupyterhub's mistake, There is an issue on [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1810) which says the prerequisite about default storageclass is needed on docs.

But, As a matter of jupyterflow uses the jupyterhub, I think the prerequisite of default storageclass should be commented in the "Setup guide" for jupyterflow.

**Comment by hongkunyoo** [comment]
Thank you for your suggestion and sorry for late reply.
I will add some prerequisite for Default Storage settings on documentations.
