### ISSUE TITLE
please come present at Argo community meeting

### ISSUE THREAD

**Issue by alexec** [hongkunyoo/jupyterflow#6]

**Comment by hongkunyoo** [comment]
Hello, @alexec sorry for late reply.
It would be wonderful to have that kind of opportunity!

**Comment by alexec** [comment]
our meetings are on the 3rd Wednesday of the month at 10am Pacific time, could you do this month?

**Comment by hongkunyoo** [comment]
Got it. 6/16 (Wed) 10 AM. Pacific time.
I will do it in this month meeting. How long do I have?

**Comment by alexec** [comment]
People talk between 5m and 30m. We could have a zoom to discus if you like?

**Comment by hongkunyoo** [comment]
Yes, It will be nice to have a zoom for some details.
I'm in Korea, which there is 16 hours lag. Please let me know when you are available for zoom.

**Comment by alexec** [comment]
Are you on CNCF slack?
